version: "3.8"
services:
  mongodb:
    container_name: mongoo
    image: mongo:latest
    volumes:
      - ./backend/data:/data
    ports:
      - "27018:27018"

  backend:
    container_name: backendd
    build: ./backend
    env_file:
      - ./backend/.env.sample
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  frontend:
    container_name: frontendd
    build: ./frontend
    env_file:
      - ./frontend/.env.sample
    ports:
      - "5173:5173"
      
volumes:
  data:
